services:
  mongo:
    image: mongo:7
    container_name: webaesthetic-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - webnet

  mongo-express:
    image: mongo-express:1
    container_name: webaesthetic-mongo-express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-example}@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - webnet

  ackee:
    image: electerious/ackee:latest
    container_name: webaesthetic-ackee
    restart: unless-stopped
    environment:
      - ACKEE_MONGODB=mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-example}@mongo:27017/ackee?authSource=admin
      - ACKEE_USERNAME=${ACKEE_USERNAME:-admin}
      - ACKEE_PASSWORD=${ACKEE_PASSWORD:-changeme}
      - ACKEE_ALLOW_ORIGIN=*
      - ACKEE_DEMO=false
    ports:
      - "3001:3000"
    depends_on:
      - mongo
    networks:
      - webnet

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: webaesthetic-web
    restart: unless-stopped
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGODB_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-example}@mongo:27017/webaesthetic?authSource=admin
      - NEXT_PUBLIC_ACKEE_SERVER=http://localhost:3001
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - webnet

volumes:
  mongo_data:

networks:
  webnet:
    driver: bridge
